language: node_js
# There isn't much gained from testing on old versions of Node. This package is
# meant to run in a browser.
node_js:
  - "node"
env:
  global:
    - secure: "fWH0G1hnlTURnwh2OTHcsX3pxXgnK06SkHFK4GKkQrSt47uRwWzXI38EsBpp79j0IIEUwJAORVnQZCax+XZrmgdBB5MfIx0fwUzercg/v5dS0YbMiAccvZ3rv0ItMpvGrtfTJFwRJcA845NK6nbd2YkN06uw+R/8aeQhWX644f3UaQjGybNXE8t9NYvfNJ0HHrRyxK3oDT6hLYvRgofbrmntA+aWdnjGsp+iA5TxAUijWuUUVJrGLdjeW1Taix1PoxHWtZh2+I7iQM4TKatSSHWjrNBvgUdBdW2pWUxdH/3hlkOULBqUqOlFAyx78K+8Hynu2FKbFSeMikmzSvffNvxFiyPe/Rvhx3wXo9bqv8axcCvG+bTfZ+WseFs83UFFyD4kQq8nQ/eDxtF7b5u6JAZ4s0UdNIbMqgvr9hhGOYayHA17LKhL1TiaIQiZWMhHFqasqRjsjnWuri/8p0mZpjnz82KydJe109zuiyvDJocwiDoyJCfEdCvziSb3taincvkPdHp95dNKj+YjTF/Z5OJ3vDDppx/vQP7rQq8yyiZzqclHqblTm/s3o+EUoEALO9XmZWtGOPj5h0MTDpMD3qNVk+7nDTBqnLvsp9xJx3YhClS3fk/4aoJm/XjgToZNJw7yz4TTidPhM1RvIEUDtP0UOIXAz/WnoNjLLNsaF8g="
    - secure: "HK4ItHH+4aKz+OxcW3dUvJJ/sciNrKiRl1iUm+YHidhuuXLWqPzU1Y74j7pj2N5rqJhC8aLt2TLNNm3odnnh39Ur4kVWE5wislhGeBdvrTWutgA16hZSzPRiekHwVQ2VcZP6eiLKKz2aOOQpfdPgbkQCsHyI5pIOW/w7pikl1mp1jHQ7F3KiHyVAwgPB+K0+QiTtVyoYqUSMV8+9wApR0mnRRDS7x7CcefPfC6l9fVpYtPOfmJKyM2MI/g+hNhaTmsCG3nXirHLW3SfiXp8yi7H9oXZ9ptns7y01JwUkMw9TsPdFv8e78X5l/EW8ZX36u5HnvrBAa6rYcSWlmkC1Y/PvQKRHmVqNepIXAszBl/GfXApjDGjmtCXXSYHa7BXCozwKVdrwHjCIT7Y8GrKXybZR2ydcOPjAAnhC9Ec9YSDmWzK1+hjdpMGujCkUIWFZHCK23uvz0WWXyADqvhz9rDFZnYSGin+S5QJn1TfCHNgcsyVO+4JqZF0T3IEzUlmnL2lo1bc9SWlOiz/abcT7s+ToXT/BWcOZeAcSPebTLfzj3R3qXuq5Ap2ojV/s8HvNCl8P55YrXTB0qJh6sUeU7mlxKr9XxE39c1x8TTgntsnQh3jva4Jc4ODtRLJY1HLX2VM3Uc51V0l7nRhiscnKvBLbnLgsy786eYAIOSls6aU="
# Developers do not need coveralls installed locally while developing. So
# there's no great benefit to adding it to devDependencies. Instead, we install
# it here.
before_script: npm i --no-save coveralls
script: npm run build-and-test -- --browsers=all
after_success: ./node_modules/.bin/coveralls < coverage/lcov.info
